### ISSUE TITLE
[table] 高度自适应问题

### ISSUE THREAD

**Issue by sweetwisdom** [Tencent/tdesign-vue#2725]
### tdesign-vue 版本

1.6.2

### 重现步骤

flex 布局如何实现表格高度自适应，像el-table那样

```scss
* {
    margin: 0;
    padding: 0;
}

.page {
    display: flex;
    flex-direction: column;

    width: 100%;
    height: 100vh;

    .header {
        height: 60px;
        line-height: 60px;
        text-align: center;
        font-weight: bold;
        font-size: 25px;
        font-weight: bolder;

    }

    .table {
        flex: 1;
        margin: 0 auto;
        width: 1000px;

      
        overflow: hidden;
       
      

    }

    .footer {
        height: 60px;
        line-height: 60px;
        text-align: center;
        font-weight: bold;
        font-size: 25px;
        font-weight: bolder;
    }
}

```

```html


<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />

    <link rel="stylesheet" href="./main.css" />
    <link rel="stylesheet" href="https://unpkg.com/tdesign-vue@1.6.2/dist/tdesign.min.css" />
    <script src="https://unpkg.com/vue@2.6/dist/vue.js"></script>
    <script src="https://unpkg.com/@vue/composition-api@1.7.2/dist/vue-composition-api.prod.js"></script>
    <script src="https://unpkg.com/tdesign-vue@1.6.2/dist/tdesign.min.js"></script>
  </head>
  <body>
    <div id="app">
      <div class="page">
        <div class="header">20XXXX年XX月XX日XXXXX数据</div>
        <div class="table">
          <t-table style="height: 100% !important" v-if="columns" bordered resizable  resizable :data="tableData" :columns="columns" :rowspan-and-colspan="rowspanAndColspan" row-key="a1"> </t-table>
        </div>
        <div class="footer"></div>
      </div>
    </div>
  </body>

 
  
</html>


```

参照：
![image](https://github.com/Tencent/tdesign-vue/assets/57869305/83997abf-5454-4340-a435-460d515742cd)
