### ISSUE TITLE
[Dialog] dialog 的 header 头部特别长时，会变形

### ISSUE THREAD

**Issue by Wonder233** [Tencent/tdesign-vue#590]
### tdesign-vue 版本

0.36.0

### 重现链接

https://codesandbox.io/s/tdesign-vue-demo-forked-myydxn?file=/src/demo.vue

### 重现步骤

正常显示如下：
<img width="496" alt="image" src="https://user-images.githubusercontent.com/8199240/158954873-dde22bff-e4f8-44bd-b91a-5cbd9fb3bc1f.png">

一旦头部过长则显示如下（图标显示变形）：
<img width="502" alt="image" src="https://user-images.githubusercontent.com/8199240/158955823-4b7b8867-9cfd-4421-b34b-13e32fe5793d.png">

有时头部还会被 [x] 按钮遮挡
<img width="504" alt="image" src="https://user-images.githubusercontent.com/8199240/158956862-9873fb86-7b7d-404f-bb0c-71084501bf79.png">

### 期望结果

图标不要变形，文字不要被遮挡

**Comment by Wonder233** [comment]
```css
::v-deep .t-dialog {
    padding-right: 45px;
    word-break: break-all;

    .t-dialog__header {

      .t-icon {
        flex-shrink: 0;
      }
    }
  }
```
